### PR TITLE
`delete project after all` property should not scale down services

### LINKED ISSUE #342: Feature: Don't scale down OpenShift resources if required
To be able to investigate what happened with OpenShift scenario and its services it will be handy to leave resources untouched after the test has been executed (e.x. if the test failed and we want to see pod logs)

Currently, we have only property `-Dts.openshift.delete.project.after.all=false` which won't remove resources, however, it will scale them down.

Implementation ideas: the new property can be introduced which will be used along with `-Dts.openshift.delete.project.after.all=false`. Because some modules contain more than one OpenShift test we can't bind property `-Dts.openshift.delete.project.after.all=false` to do both (not delete + not scale down) (I guess)

### PR DESCRIPTION
**Pull request by pjgg**
`ts.kubernetes.delete.project.after.all=false` should not scale down k8s/ocp services
Also must only works if `ts.kubernetes.ephemeral.namespaces.enabled=false`

Close #342

### CODE REVIEW

**Comment by pjgg** [comment]
Pinpong serverless scenario `OpenShiftUsingExtensionAndDockerBuildAndServerlessPingPongResourceIT` is failling by an error not related to this PR 

```
SEVERE Caught exception while closing extension context: org.junit.jupiter.engine.descriptor.ClassExtensionContext@14823f76: javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
```

**Review by Sgitario — CHANGES_REQUESTED** [review]
If you add this code in the stop methods, then when calling the stop method in a test scenario, it wont work. The user would expect the app is stopped but it wont because the ephemeral was enabled...

Therefore, this is not a suitable fix.

Moreover, in k8s there are now two properties: "ts.kubernetes.delete.project.after.all" (this was created here and "ts.kubernetes.delete.namespace.after.all" (the good one as k8s does not know what a project is - this concept is from ocp)

File: quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/KubernetesExtensionBootstrap.java [hunk 1]
```diff
@@ -16,16 +16,28 @@
 
     private static final PropertyLookup DELETE_NAMESPACE_AFTER = new PropertyLookup("ts.kubernetes.delete.namespace.after.all",
             Boolean.TRUE.toString());
+    private static final PropertyLookup DELETE_PROJECT_AFTER = new PropertyLookup("ts.kubernetes.delete.project.after.all",
```
Comment (Sgitario) [inline quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/KubernetesExtensionBootstrap.java:19]: This property does not make sense in k8s, we should use `DELETE_NAMESPACE_AFTER` instead.

File: quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/KubernetesExtensionBootstrap.java [hunk 2]
```diff
@@ -16,16 +16,28 @@
...
+    private static final PropertyLookup ENABLED_EPHEMERAL_NAMESPACES = new PropertyLookup(
+            "ts.kubernetes.ephemeral.namespaces.enabled", Boolean.TRUE.toString());
 
     private KubectlClient client;
 
     @Override
     public boolean appliesFor(ScenarioContext context) {
-        return context.isAnnotationPresent(KubernetesScenario.class);
+        boolean isValidConfig = context.isAnnotationPresent(KubernetesScenario.class);
+        if (isValidConfig && !DELETE_PROJECT_AFTER.getAsBoolean() && ENABLED_EPHEMERAL_NAMESPACES.getAsBoolean()) {
```
Comment (Sgitario) [inline quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/KubernetesExtensionBootstrap.java:29]: This logic is wrong, if the KubernetesScenario annotation is not present, we should not check those properties.

File: quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/KubernetesExtensionBootstrap.java [hunk 3]
```diff
@@ -16,16 +16,28 @@
...
+                    + " -Dts.kubernetes.ephemeral.namespaces.enabled=false");
+            isValidConfig = false;
+        }
+
+        return isValidConfig;
     }
 
     @Override
     public void beforeAll(ScenarioContext context) {
+        context.setDebug(!DELETE_PROJECT_AFTER.getAsBoolean() && !ENABLED_EPHEMERAL_NAMESPACES.getAsBoolean());
```
Comment (Sgitario) [inline quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/KubernetesExtensionBootstrap.java:40]: nitpick comment: I would add a comment explaining your purpose here: explain better why it should be set DEBUG if these two properties are set.

File: quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/KubernetesExtensionBootstrap.java [hunk 4]
```diff
@@ -16,16 +16,28 @@
 
     private static final PropertyLookup DELETE_NAMESPACE_AFTER = new PropertyLookup("ts.kubernetes.delete.namespace.after.all",
             Boolean.TRUE.toString());
+    private static final PropertyLookup DELETE_PROJECT_AFTER = new PropertyLookup("ts.kubernetes.delete.project.after.all",
+            Boolean.TRUE.toString());
+    private static final PropertyLookup ENABLED_EPHEMERAL_NAMESPACES = new PropertyLookup(
```
Comment (Sgitario) [inline quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/KubernetesExtensionBootstrap.java:21]: This property definition is duplicated in KubectlClient

File: quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/OpenShiftExtensionBootstrap.java [hunk 5]
```diff
@@ -20,16 +20,26 @@
             Boolean.TRUE.toString());
     private static final PropertyLookup DELETE_PROJECT_AFTER = new PropertyLookup("ts.openshift.delete.project.after.all",
             Boolean.TRUE.toString());
+    private static final PropertyLookup ENABLED_EPHEMERAL_NAMESPACES = new PropertyLookup(
```
Comment (Sgitario) [inline quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/OpenShiftExtensionBootstrap.java:23]: This property definition is duplicated in OpenShiftClient.

File: quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/OpenShiftExtensionBootstrap.java [hunk 6]
```diff
@@ -20,16 +20,26 @@
...
+            "ts.openshift.ephemeral.namespaces.enabled", Boolean.TRUE.toString());
 
     private OpenShiftClient client;
 
     @Override
     public boolean appliesFor(ScenarioContext context) {
-        return context.isAnnotationPresent(OpenShiftScenario.class);
+        boolean isValidConfig = context.isAnnotationPresent(OpenShiftScenario.class);
+        if (isValidConfig && !DELETE_PROJECT_AFTER.getAsBoolean() && ENABLED_EPHEMERAL_NAMESPACES.getAsBoolean()) {
```
Comment (Sgitario) [inline quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/OpenShiftExtensionBootstrap.java:31]: This logic is wrong, if the OpenShiftScenario annotation is not present, we should not check those properties.

File: quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/OpenShiftExtensionBootstrap.java [hunk 7]
```diff
@@ -20,16 +20,26 @@
...
+                    + " -Dts.openshift.ephemeral.namespaces.enabled=false");
+            isValidConfig = false;
+        }
+
+        return isValidConfig;
     }
 
     @Override
     public void beforeAll(ScenarioContext context) {
+        context.setDebug(!DELETE_PROJECT_AFTER.getAsBoolean() && !ENABLED_EPHEMERAL_NAMESPACES.getAsBoolean());
```
Comment (Sgitario) [inline quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/OpenShiftExtensionBootstrap.java:42]: nitpick comment: I would add a comment explaining your purpose here: explain better why it should be set DEBUG if these two properties are set.

**Review by Sgitario — CHANGES_REQUESTED** [review]

File: quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/KubernetesExtensionBootstrap.java (hunk 2 above)
Comment (Sgitario) [reply quarkus-test-kubernetes/src/main/java/io/quarkus/test/bootstrap/KubernetesExtensionBootstrap.java:29]: I read this wrongly. Deleted.

**Review by Sgitario — APPROVED** [review]
